🐛 Fix serialization error in /admin/reporting
  Order items with null _id (old orders, backwards compatibility)
  caused 'Cannot read properties of null' error.

  Added optional chaining for item._id?.toString()

  Error: Cannot stringify arbitrary non-POJOs (data.orders[0].items[0]._id)